paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      description: Obtiene todos los productos de la base de datos
      operationId: getProducts
      tags:
        - products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      summary: Crea un nuevo producto
      description: Crea un nuevo producto en la base de datos
      operationId: createProduct
      tags:
        - products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /api/products/{id}:
    get:
      summary: Obtiene un producto
      description: Obtiene un producto buscando por su id
      operationId: getProductById
      tags:
        - products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID de producto
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    put:
      summary: Actualiza un producto
      description: Actualiza un producto buscando por su id
      operationId: updateProduct
      tags:
        - products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID de producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Elimina un producto
      description: Elimina un producto buscando por su id
      operationId: deleteProduct
      tags:
        - products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID de producto
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID autogenerado de Mongo
        title:
          type: string
          description: Nombre del producto
          unique: true
          required: true
        description:
          type: string
          description: Descripción del producto
          required: true
        category:
          type: string
          description: Categoría del producto
          required: true
          enum:
            - Monitores
            - Periféricos
            - Procesadores
            - Memorias RAM
            - Almacenamiento
            - Placas de video
            - Laptops
        price:
          type: number
          description: Precio del producto
          required: true
        thumbnails:
          type: array
          description: Imágenes del producto
          items:
            type: string
        code:
          type: string
          description: Código del producto
          required: true
        stock:
          type: string
          description: Stock del producto
          required: true
        status:
          type: boolean
          description: Estado del producto
          default: true
        owner:
          type: mongoose.Schema.Types.ObjectId
          description: ID del usuario dueño del producto
          ref: 'User'
          default: 'admin'
      example:
        title: Monitor 24"
        description: Monitor de 24 pulgadas
        category: Monitores
        price: 20000
        thumbnails:
          - https://www.example.com/image1.jpg
          - https://www.example.com/image2.jpg
        code: MON24
        stock: 10
        status: true
        owner: 60b6b1b3b3b3b3b3b3b3b3b3
    Cart:
      type: object
      properties:
        date:
          type: date
          description: Fecha de creación del carrito
          required: true
        products:
          type: array
          description: Productos del carrito
          items:
            type: object
            description: Producto del carrito
            properties:
              product:
                type: mongoose.Schema.Types.ObjectId
                description: ID del producto
                ref: 'products'
              quantity:
                type: number
                description: Cantidad del producto
                default: 1
      example:
        date: 2021-06-01
        products:
          - product: 60b6b1b3b3b3b3b3b3b3b3b3
            quantity: 2
          - product: 60b6b1b3b3b3b3b3b3b3b4
            quantity: 1